name: Print workflow trigger
description: |
  Print the event that triggered the workflow

inputs: {}

runs:
  using: "composite"
  steps:
    - name: Show action trigger
      uses: actions/github-script@v7
      with:
        script: |
          const eventName = context.eventName;
          const eventAction = context.payload.action || 'N/A';
          const actor = context.actor;
          console.log(`The job was triggered by a ${eventName} event.`);
          console.log(`  - Event action: ${eventAction}`);
          console.log(`  - Triggered by: ${actor}`);
