name: mappy hello world

on:
  # Runs every time a PR is open against master
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, labeled, ready_for_review, reopened]
  workflow_dispatch:

jobs:
  hello-mappy:
    if: ${{ github.event.repository.name == 'scream' }}
    runs-on: [self-hosted, mappy]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Show action trigger
        run: |
          echo "= The job was automatically triggered by a ${{github.event_name}} event."
      - name: greet the world
        run: echo "hello world"
      - name: list mods
        run: module list
