name: PR Testing

on:
  # Runs on PRs against master
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, ready_for_review, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on:  [self-hosted, openmp, gcc]
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Show action trigger
        uses: actions/github-script@v6
        with:
          script: |
            const eventName = context.eventName;
            const eventAction = context.payload.action || 'N/A';
            const actor = context.actor;
            console.log(`The job was triggered by a ${eventName} event.`);
            console.log(`  - Event action: ${eventAction}`);
            console.log(`  - Triggered by: ${actor}`);
      - name: Cache repository
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .
          key: ${{ runner.os }}-repo-${{ github.sha }}
        env:
          NODE_EXTRA_CA_CERTS: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      - name: Check out the repository
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
          submodules: recursive
      - name: Update cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: |
            .
          key: ${{ runner.os }}-repo-${{ github.sha }}
        env:
          NODE_EXTRA_CA_CERTS: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

  test-all-scream:
    needs: setup
    runs-on: [self-hosted, openmp, gcc]
    strategy:
      fail-fast: false
      matrix:
        build_type: [sp, dbg, fpe, opt]
        device: [openmp]
        compiler: [gcc]
    name: ${{ matrix.compiler }}-${{ matrix.device }}-${{ matrix.build_type }}
    steps:
      - name: Restore repository cache
        uses: actions/cache@v3
        with:
          path: |
            .
          key: ${{ runner.os }}-repo-${{ github.sha }}
        env:
          NODE_EXTRA_CA_CERTS: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      - name: Fail if no cache is found
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found. Failing the job."
          exit 1
      - name: Run tests
        uses: ./.github/actions/test-all-scream
        with:
          build_type: ${{ matrix.build_type }}
          machine: ghci-snl-${{ matrix.device }}
          run_type: at-run
